%!TEX TS-program = xelatex
%!TEX encoding = UTF-8 Unicode

\documentclass[12pt]{article}
\usepackage{geometry} 
\geometry{letterpaper}
\usepackage{graphicx}
\usepackage{amssymb}
\usepackage{longtable}
\usepackage{rotating}
\usepackage{booktabs}
\usepackage[table]{xcolor}
\usepackage{colortbl}
\usepackage{float}
\restylefloat{table}
\usepackage[colorlinks,urlcolor=blue]{hyperref}

\usepackage{fontspec,xltxtra,xunicode}
\defaultfontfeatures{Mapping=tex-text}
\setromanfont[Mapping=tex-text]{Hoefler Text}
\setsansfont[Scale=MatchLowercase,Mapping=tex-text]{Gill Sans}
\setmonofont[Scale=MatchLowercase]{Andale Mono}

\begin{document}

\section*{Colour coded cufflinks flags}
\href{https://github.com/kn3in/rnaseq-util}{Script} to convert cufflinks gtf to colour coded bed.


<<label=web, echo=FALSE, result=tex>>=
#--------------------------
library(XML)
library(xtable)
library(stringr)
#--------------------------
html <- "http://cufflinks.cbcb.umd.edu/manual.html"
html <- htmlParse(html)
tables <- readHTMLTable(html)
flags <- tables[[14]]
flags <- flags[ ,1:3]
colnames(flags) <- flags[1,]
flags <- flags[-1, ]
rownames(flags) <- NULL
flags$Description <- str_replace_all(str_replace_all(flags$Description, "\n\t\t\t\t", " "), "\\s+", " ")
flags$col <- c("black", "gray", "steelblue", "darkmagenta", "darkolivegreen", "pink4", "darkorange1", "cadetblue4", "darkred", "bisque4", "chartreuse", "darkorchid4")
flags$paint <- ""
#--------------------------
x <- xtable(flags)
my_col <- format(as.data.frame(t(col2rgb(x$col)))/255, digits=2)
rgbCols <- do.call("paste", c(my_col, sep=","))
x$paint <- paste("\\cellcolor[rgb]{", rgbCols, "}", x$paint, sep="")
align(x) <- "lllp{8cm}ll"
print(x, 
      include.rownames=FALSE,
      table.placement="H",
      sanitize.text.function = function(x) gsub("%", "\\%", x, fixed=TRUE))

@

\end{document}